[package]
name = "kontor"
version = "0.1.0"
edition = "2024"

[dependencies]
backon = { version = "1.4", features = ["tokio-sleep"] }
anyhow = "1"
base64 = "0.22.1"
bitcoin = { version = "0.32.5", features = ["serde"] }
deadpool = "0.12.2"
libsql = "0.6.0"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde-env = "0.2.0"
serde_json = "1"
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.13"
tracing = "0.1"
tracing-subscriber = "0.3"
zmq = "0.10.0"
scopeguard = "1.2.0"
rayon = "1.10.0"
indexmap = "2.7.1"
