[package]
name = "stdlib"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
macros = { path = "../macros" }
wasm-wave = { version = "0.238.1"}

[dev-dependencies]
macrotest = "=1.2.0"
trybuild = "=1.0.110"
