[workspace]
members = ["indexer", "macros", "stdlib", "testlib"]
resolver = "2"

[workspace.lints.clippy]
new_without_default = "allow"
uninlined_format_args = "allow"
too_many_arguments = "allow"

[workspace.dependencies]
# IMPORTANT
wasmtime = { version = "=38.0.4", features = ["wave", "component-model-async"] }
wit-bindgen = "=0.48.0"
wit-component = "=0.241.2"
wit-parser = "=0.241.2"
wasm-wave = "0.241.2"

anyhow = "=1.0.100"
axum = { version = "=0.8.7", features = ["http2", "ws"] }
bon = "=3.8.1"
tokio = { version = "=1.48.0", features = ["full"] }
tower-http = { version = "=0.6.6", features = [
  "fs",
  "trace",
  "compression-full",
  "request-id",
  "timeout",
  "catch-panic",
  "cors",
] }
tower = "=0.5.2"
tracing = "=0.1.41"
libsql = "=0.9.27"
glob = "=0.3.3"
async-trait = "=0.1.89"
tempfile = "=3.23.0"
serial_test = "=3.2.0"
