[workspace]
members = ["indexer", "macros", "stdlib", "testlib", "ui"]
resolver = "2"

[workspace.lints.clippy]
new_without_default = "allow"
uninlined_format_args = "allow"

[workspace.dependencies]
# IMPORTANT
wasmtime = { version = "36.0.2", features = ["wave"] }
wit-component = "0.238"
wit-parser = "0.238"
wasm-wave = "0.238"

anyhow = "1"
axum = { version = "0.8", features = ["http2", "ws"] }
bon = "3.7"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6", features = [
  "fs",
  "trace",
  "compression-full",
  "request-id",
  "timeout",
  "catch-panic",
  "cors",
] }
tower = "0.5"
tracing = "0.1"
libsql = "0.9.21"
