[workspace]
members = ["indexer", "macros", "stdlib", "testlib", "ui"]
resolver = "2"

[workspace.lints.clippy]
new_without_default = "allow"
uninlined_format_args = "allow"

[workspace.dependencies]
# IMPORTANT
wasmtime = { version = "=36.0.2", features = ["wave", "component-model-async"] }
wit-component = "=0.239.0"
wit-parser = "=0.239.0"
wasm-wave = "=0.239.0"

anyhow = "=1.0.99"
axum = { version = "=0.8.4", features = ["http2", "ws"] }
bon = "=3.7.2"
tokio = { version = "=1.47.1", features = ["full"] }
tower-http = { version = "=0.6.6", features = [
  "fs",
  "trace",
  "compression-full",
  "request-id",
  "timeout",
  "catch-panic",
  "cors",
] }
tower = "=0.5.2"
tracing = "=0.1.41"
libsql = "=0.9.23"
