[workspace]
members = ["arith", "crypto", "fib", "proxy", "token"]
resolver = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"

[workspace.lints.clippy]
new_without_default = "allow"
uninlined_format_args = "allow"

[workspace.dependencies]
# IMPORTANT
wit-bindgen = "0.44.0"
wasm-wave = "0.236"

macros = { path = "../core/macros" }
stdlib = { path = "../core/stdlib" }
