[package]
name = "kontor_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
tower = { workspace = true }
http = "1.0"
hyper = { version = "1.0", features = ["full"] }